// EX['base|tier'] = [5개 explain] — 정답 클릭 시 '왜 그런가'. HTML 허용.
module.exports = {
// ══ 값 챕터 ══
'1|easy':[
 '<b>typeof</b>는 값의 종류 이름을 준다. 숫자는 <code>"number"</code>.',
 '따옴표로 감싼 값은 <b>문자열</b> → <code>"string"</code>.',
 '<code>true</code>·<code>false</code>는 <b>불리언</b> → <code>"boolean"</code>.',
 '<code>x = x + 5</code>는 <b>지금 x의 값(10)에 5를 더한 15</b>를 다시 x에 담는다.',
 '원시값은 <code>=</code>로 넘길 때 <b>값을 복제</b>한다. b를 바꿔도 a의 셀은 그대로 10.',
],
'1|normal':[
 '왼쪽부터: <code>1+1=2</code>, 그다음 <code>2*3=6</code>.',
 '숫자끼리의 계산 결과도 숫자 → <code>"number"</code>.',
 '숫자+글자는 <b>글자로 끌려간다</b>(2강) → <code>"1"+"2"="12"</code>는 문자열.',
 'b는 대입 순간 값 10을 <b>복제</b>. 나중에 a만 바꿔도 b는 10.',
 '<code>+</code>는 한쪽이 글자면 <b>이어붙이기</b> → <code>"5"+3="53"</code>.',
],
'1|hard':[
 '<code>typeof null</code>은 <b>"object"</b> — JS 초창기 버그가 호환성 때문에 남았다.',
 'NaN은 "숫자가 아님"이지만 <b>타입은 number</b>(실패한 숫자 계산 결과).',
 '0.1·0.2는 2진 소수로 딱 안 떨어져 <b>미세 오차</b>가 생겨 0.3과 다르다.',
 '<code>-</code>는 <code>"5"</code>를 <b>숫자 5로 강제</b> → <code>5-1=4</code>. (+와 반대)',
 '선언만 하고 값을 안 넣은 변수는 <code>undefined</code>.',
],
'2|easy':[
 '둘 다 숫자라 <b>산술 덧셈</b> → 7.',
 '<code>+</code>에 글자가 끼면 <b>이어붙이기</b> → 숫자 4가 문자로 → <code>"34"</code>.',
 '문자열끼리 <code>+</code>는 이어붙이기 → <code>"가나"</code>.',
 '템플릿 <code>${n}</code> 자리에 n의 값 5가 끼워진다 → <code>"5점"</code>.',
 '이어붙여 <code>"abcd"</code>.',
],
'2|normal':[
 '왼쪽부터: <code>1+2=3</code>, 다음 <code>3+"3"</code>은 글자 이어붙이기 → <code>"33"</code>.',
 '첫 <code>"3"+2</code>가 이미 문자 <code>"32"</code>, 이어서 <code>+1="321"</code>.',
 '문자열 <code>.length</code>는 글자 수 → 3.',
 '<code>${a+b}</code>는 <b>먼저 계산</b>돼 5가 끼워진다.',
 '<code>toUpperCase()</code>는 전부 대문자로 → <code>"HI"</code>.',
],
'2|hard':[
 '<code>*</code>는 글자를 <b>숫자로 강제</b> → <code>5*2=10</code>. (+와 반대)',
 '<code>+</code>에 빈 글자가 끼면 숫자가 <b>문자로</b> → <code>"10"</code>. 숫자→문자 변환 관용구.',
 '문자열도 <b>번호로 접근</b> → 1번 글자 <code>"b"</code>.',
 '<code>split(",")</code>는 쉼표로 잘라 배열 <code>["a","b","c"]</code> → 길이 3.',
 '<code>Number("12")</code>는 문자를 숫자 12로 → <code>12+3=15</code>.',
],
'3|easy':[
 '곱셈이 덧셈보다 먼저 → <code>3*4=12</code>, <code>+2=14</code>.',
 '괄호가 최우선 → <code>(2+3)=5</code>, <code>*4=20</code>.',
 '같은 우선순위는 <b>왼쪽부터</b> → <code>(10-2)-3=5</code>.',
 '곱셈 둘이 먼저 → <code>6</code>과 <code>20</code>, 더해 26.',
 '곱셈 먼저 → <code>2*3=6</code>, <code>5+6=11</code>.',
],
'3|normal':[
 '괄호 안 <code>1+2=3</code> 먼저, 그다음 문자 이어붙이기 → <code>"n=3"</code>.',
 '인자 안 <code>2*3=6</code> 먼저 계산 → <code>max(1,6)=6</code>.',
 '삼항도 <b>값을 내는 식</b> → <code>7>3</code>이 참이라 <code>"y"</code>.',
 '<code>&lt;</code>가 <code>&amp;&amp;</code>보다 먼저 → <code>true&lt;true=false</code>, <code>false&amp;&amp;true=false</code>.',
 '<code>%</code>는 나눈 나머지 → <code>10=3·3+1</code> → 1.',
],
'3|hard':[
 '<code>2**3</code>은 2의 3제곱 → 8.',
 '왼쪽부터: <code>1+2=3</code>, <code>3+"3"</code>은 글자 → <code>"33"</code>.',
 '<code>-</code>는 <code>"5"</code>를 숫자 5로 강제 → <code>5-1=4</code>.',
 'true가 숫자 1로 강제 → <code>1+1=2</code>.',
 '<code>&gt;</code>가 먼저: <code>10&gt;5=true</code>, <code>true===true=true</code>.',
],
'4|easy':[
 '10은 5보다 크다 → 참.',
 '<code>&gt;=</code>는 "크거나 <b>같음</b>"도 참 → true.',
 '5와 5는 같으니 "<b>다르다</b>(!==)"는 거짓.',
 '<code>===</code>는 <b>타입까지</b> 본다. 문자 "5"≠숫자 5 → false.',
 '7은 10보다 작거나 같다 → 참.',
],
'4|normal':[
 '0은 <b>falsy</b>(거짓 취급) → <code>Boolean(0)=false</code>.',
 '빈 문자열은 falsy → false.',
 '<b>빈 배열도 객체</b> → truthy → true. (내용 아니라 "존재"로 판단)',
 '<code>"false"</code>는 5글자짜리 <b>문자열</b>(값이 있음) → truthy → true.',
 '공백 한 칸도 <b>글자 1개</b> → truthy → true.',
],
'4|hard':[
 '<code>&amp;&amp;</code>는 참/거짓이 아니라 <b>피연산자 자체</b>를 돌려준다 → 둘 다 참이면 뒤쪽 2.',
 '<code>||</code>는 <b>참인 쪽 피연산자</b>를 돌려준다 → 0은 falsy라 <code>"안녕"</code>.',
 '왼쪽부터: <code>2&gt;1=true</code>, <code>true</code>가 1로 강제 → <code>1&gt;0=true</code>.',
 'NaN은 <b>자기 자신과도 같지 않게</b> 정의돼 있다 → false. (유일한 예외)',
 '느슨한 <code>==</code>는 양쪽을 숫자로 강제: <code>""→0</code>, <code>0==0=true</code>.',
],
'5|easy':[
 '함수는 입력→처리→<b>출력(return)</b> → <code>2+3=5</code>.',
 '인수 4가 매개변수 n에 담겨 <code>4*2=8</code>.',
 '받은 <code>"z"</code>에 <code>"님"</code>을 이어붙여 반환.',
 '<code>5*5=25</code>를 돌려준다.',
 '<code>return</code>이 없으면 함수는 <b>undefined</b>를 돌려준다.',
],
'5|normal':[
 '안쪽부터: <code>twice(3)=6</code>, <code>twice(6)=12</code>.',
 '화살표 함수도 같은 함수 → <code>6*2=12</code>.',
 '<code>100 + 100*0.1 = 110</code>(세금 10 포함).',
 '-2는 양수가 아니라 삼항의 else → <code>"-"</code>.',
 '함수 안에서 <b>바깥 base(10)</b>를 읽어 <code>5+10=15</code>.',
],
'5|hard':[
 '함수 안 지역 n=1이 <b>바깥 n=9를 가린다</b>(스코프) → 1.',
 '<code>make()</code>가 함수를 돌려주고, 그걸 <code>()</code>로 또 불러 7.',
 '인수는 <b>복사</b>라 함수 안 x를 바꿔도 밖 a는 5.',
 '-1은 첫 return을 건너뛰고 <b>아래 return</b> → <code>"음"</code>.',
 '콜백 dbl이 각 요소에 적용 → 첫 요소 <code>1*2=2</code>.',
],
'6|easy':[
 '<code>.length</code>는 요소 개수 → 4.',
 '번호는 <b>0부터</b> → 1번은 두 번째 20.',
 '요소가 없으면 개수 0.',
 '<code>push</code>는 끝에 하나 추가 → <code>3+1=4</code>.',
 '마지막 번호는 <code>length-1</code> → <code>a[2]=3</code>.',
],
'6|normal':[
 '0번을 9로 바꾼 뒤 <code>a[0]+a[1] = 9+2 = 11</code>.',
 '<code>push(3,4)</code>는 한 번에 둘 추가 → <code>2+2=4</code>.',
 '<code>includes(2)</code>는 담고 있으면 true.',
 '<code>indexOf("c")</code>는 위치(0부터) → 2.',
 '<code>pop</code>은 끝을 하나 빼 → <code>3-1=2</code>.',
],
'6|hard':[
 '<code>join("-")</code>은 요소 사이에 "-"를 끼워 문자열 → <code>"1-2-3"</code>.',
 '<b>배열은 참조</b> → b·a가 같은 배열이라 b에 push하면 a도 늘어 4.',
 '기본 <code>sort()</code>는 <b>문자로 비교</b> → "100"&lt;"20"&lt;"3" → 첫째 100. (함정)',
 'JS엔 <b>음수 인덱스가 없다</b> → 없는 칸 <code>undefined</code>. (파이썬과 다름)',
 '<code>filter(x&gt;2)</code>는 3,4만 남겨 개수 2.',
],
'7|easy':[
 '<code>map</code>은 각 요소를 변환한 새 배열 → 첫 요소 <code>1*2=2</code>.',
 '각 요소 +1 → 마지막 <code>3+1=4</code>.',
 '<code>filter</code>는 조건 맞는 것만 → 3,4 두 개.',
 '<code>reduce</code>로 누적 합 → <code>10+20+30=60</code>.',
 '<code>forEach</code>로 sum에 하나씩 더해 <code>1+2+3=6</code>.',
],
'7|normal':[
 '<code>map</code>은 <b>새 배열을 만들 뿐 원본은 그대로</b> → 개수 3.',
 '짝수(나머지 0)만 → 2,4,6 세 개.',
 '<code>reduce</code>로 곱 누적 → <code>2×3×4=24</code>(시작 1).',
 '<code>toUpperCase</code>로 대문자 → 첫 요소 <code>"A"</code>.',
 '체이닝: <code>filter</code>로 [2,3] → <code>map</code>으로 [4,6] → 첫째 4.',
],
'7|hard':[
 '시작값 없는 reduce는 <b>첫 요소를 그대로 시작값</b>으로 → 요소 하나면 5.',
 '<code>find</code>는 조건 맞는 <b>첫 값</b>을 돌려준다 → 10.',
 '<code>every</code>는 <b>모두</b> 만족하면 true.',
 '<code>map</code>으로 나이만 뽑아 <code>reduce</code>로 합 → <code>20+30=50</code>.',
 '<code>forEach</code>는 <b>반환이 없다</b> → r은 undefined. (map과 다름)',
],
'8|easy':[
 '<code>obj.키</code>로 그 속성 값을 꺼낸다 → 24.',
 '<code>car.brand</code> → <code>"기아"</code>.',
 '<code>u.hp = 50</code>으로 덮어써 50.',
 '없던 속성도 <code>=</code>로 <b>새로 추가</b>된다.',
 '<b>없는 키</b>를 꺼내면 에러가 아니라 <code>undefined</code>.',
],
'8|normal':[
 '점을 이어 <code>me.pet.name</code> → <code>"콩이"</code>.',
 '<code>users[1]</code>은 두 번째 객체 → <code>.name="지훈"</code>.',
 '공백 있는 키는 <b>대괄호</b>로만 → <code>o["my key"]=7</code>.',
 '속성을 이어붙여 <code>"민지(24)"</code>.',
 '<code>Object.keys(o)</code>는 키 배열 <code>["a","b"]</code> → 길이 2.',
],
'8|hard':[
 '값이 함수인 속성 = <b>메서드</b> → <code>dog.bark()</code>가 <code>"멍"</code>.',
 '점·번호를 이어 끝까지 → <code>data.users[0].pet.name="콩이"</code>.',
 '각 사람의 age를 누적 → <code>24+30=54</code>.',
 'vip가 참이라 <code>"⭐"</code>가 붙어 <code>"민지⭐"</code>.',
 '메서드 안 <code>this</code>는 <b>자기 객체</b> → <code>this.name="민지"</code>.',
],
'9|easy':[
 '<code>textContent</code>에 넣은 글자를 그대로 읽는다.',
 '<code>style.color</code>에 정한 색을 읽는다.',
 '<code>className</code>에 정한 클래스를 읽는다.',
 '<code>id</code>에 정한 값을 읽는다.',
 '<code>append</code>로 자식 하나 붙여 <code>children.length=1</code>.',
],
'9|normal':[
 '<code>tagName</code>은 <b>항상 대문자</b>로 나온다 → <code>"BUTTON"</code>.',
 '<code>textContent</code>는 <b>항상 문자</b> → 숫자 90이 <code>"90"</code>이 된다.',
 '클릭하면 리스너가 실행돼 n이 1.',
 '리스너가 매번 +1 → 두 번 클릭 2.',
 'span 둘 붙여 <code>children.length=2</code>.',
],
'9|hard':[
 '<code>innerHTML</code>로 넣은 <code>&lt;p&gt;</code>를 골라 글자를 읽는다.',
 '<code>style.width</code>에 정한 값을 읽는다.',
 '<code>setAttribute</code>로 넣은 값을 <code>getAttribute</code>로 읽는다.',
 '<b>같은 요소는 복제가 아니라 이동</b> → 두 번 append해도 자식 1개.',
 '숫자+글자라 <code>textContent</code>가 <code>"90점"</code>.',
],
'10|easy':[
 '변수 name을 문장에 이어붙여 <code>"안녕, 민지님"</code>.',
 '<code>.length</code>로 사람 수 3.',
 '속성을 이어붙여 <code>"콩이는 3살"</code>.',
 '<code>textContent</code>에 넣은 글자 그대로.',
 '받은 이름에 <code>"님 환영!"</code>을 붙여 반환.',
],
'10|normal':[
 '15는 19 미만이라 삼항 else → <code>"청소년"</code>.',
 '<code>map</code>으로 +1 한 배열의 두 번째 <code>20+1=21</code>.',
 '클릭 리스너가 실행돼 clicked 1.',
 '<code>ppl[0].name</code> → <code>"민지"</code>.',
 '<code>reduce</code>로 합 <code>10+20=30</code>.',
],
'10|hard':[
 '속성을 이어붙인 카드 문자열 <code>"민지(24)"</code>.',
 'vip라 <code>"⭐"</code>가 붙어 <code>"민지⭐"</code>.',
 '<code>filter</code>로 25 초과(30살)만 → 1명.',
 '메서드 <code>dog.bark()</code> → <code>"멍"</code>.',
 '숫자 90이 문자로 → <code>"90점"</code>.',
],
// ══ 메모리 챕터 ══
'ram|easy':[
 '<code>x=x+5</code>는 현재 10에 5를 더한 15를 다시 담는다.',
 '숫자의 타입 이름은 <code>"number"</code>.',
 '원시값은 <b>각자 셀로 복제</b> → b를 바꿔도 a는 10. (객체면 공유 — M4-2)',
 '<code>null</code>은 "<b>일부러 비움</b>"을 뜻하는 값. (undefined=아직 없음과 구분)',
 '글자의 타입 이름은 <code>"string"</code>.',
],
'ram|normal':[
 '왼쪽부터: <code>1+1=2</code>, <code>2*3=6</code>.',
 'a를 바꿔도 b는 <b>복사본</b>이라 7 그대로.',
 '참거짓의 타입 이름은 <code>"boolean"</code>.',
 '선언만 하고 값이 없으면 <code>"undefined"</code>.',
 'v에 글자를 담으면 타입도 <b>string</b>으로 바뀐다(동적 타입).',
],
'ram|hard':[
 '<code>typeof null="object"</code> — JS의 오래된 버그(호환성 때문에 유지).',
 'NaN은 실패한 <b>숫자</b> → 타입은 number.',
 '2진 소수 오차로 <code>0.1+0.2 ≠ 0.3</code>.',
 'a는 복사라 1, b만 9 → <code>1+9=10</code>.',
 'b만 +1, a는 복제본이라 5.',
],
'ref|easy':[
 '<b>원시값 복사</b> → y를 바꿔도 x는 10.',
 'b는 자기 셀(5) → a를 바꿔도 그대로.',
 '숫자는 복사 → money1은 200 안전.',
 '문자열도 복사 → s1은 <code>"무지"</code>.',
 '<code>a.num</code>을 꺼낼 때 <b>값을 복사</b> → a.num은 10.',
],
'ref|normal':[
 '복사본 y를 곱해도 x는 3.',
 '복사본 b에서 빼도 a는 100.',
 '함수 인수도 <b>복사</b> → p는 5 안전.',
 'x·y 각자 셀 → <code>10+20=30</code>.',
 's는 <code>"a"</code> 그대로 → <code>"a"+"b"="ab"</code>.',
],
'ref|hard':[
 'b는 <code>a.v</code> 복사(1), c는 a 자체 공유 → <code>1+9=10</code>. <b>같은 =라도 원시는 복사·객체는 공유</b>.',
 'a는 복사라 1 그대로 → <code>1===1</code>은 true.',
 '함수에 원시를 넘기면 복사 → 몇 번 불러도 a는 3.',
 'a는 안 변해 4 → <code>inc(a)=5</code>, <code>5+4=9</code>.',
 't만 바꿔도 s는 <code>"hi"</code>.',
],
'ref2|easy':[
 'b는 a의 별칭(같은 힙 객체) → b.n을 바꾸면 a.n도 9.',
 'p1·p2 같은 객체 → 50.',
 '<b>배열도 참조</b> → 같은 배열이라 arr도 늘어 3.',
 'u·r 같은 객체 → <code>"지훈"</code>.',
 'x·y 같은 객체 → 5.',
],
'ref2|normal':[
 'c는 <code>a.n</code> 복사(1), b는 공유 → c는 1 그대로.',
 'a·b 같은 객체라 둘 다 9 → <code>9+9=18</code>.',
 '같은 배열에 두 번 push → 3.',
 'b를 <b>새 객체로 재할당</b>하면 a와 연결이 끊겨 a.n은 1.',
 'p·o 같은 객체라 같은 list → 3.',
],
'ref2|hard':[
 'snap은 복사(1), b는 공유(9) → <code>1+9=10</code>.',
 '재할당으로 연결 끊긴 뒤라 이후 변경은 a와 무관 → 1.',
 '함수가 공유 객체를 바꿔 b(별칭)도 0.',
 '<code>concat</code>은 <b>새 배열</b>을 만들 뿐 원본 안 바꿈 → a는 3. (push와 다름)',
 'p는 <code>me.pet</code>과 같은 객체 → 0.',
],
'stack|easy':[
 '두 매개변수를 더해 <code>3+4=7</code>.',
 '지역변수 n(10)을 반환.',
 '<code>100 + 100*0.1 = 110</code>.',
 '<code>6*2=12</code>.',
 '문자열 <code>"토끼"</code>를 반환.',
],
'stack|normal':[
 '두 매개변수를 곱해 <code>3×4=12</code>.',
 '<code>10-4=6</code>.',
 '-2는 양수 아님 → <code>"-"</code>.',
 '지역 x=5의 2배 → 10.',
 '<code>"hi "+"z"="hi z"</code>.',
],
'stack|hard':[
 'b가 5를 돌려주고 a가 2배 → 10. (프레임이 쌓였다 반환)',
 'f=+1을 세 번 → <code>0→1→2→3</code>.',
 '함수 안 n=10과 밖 n=99는 <b>다른 칸</b> → <code>10+99=109</code>.',
 '-1은 아래 return → <code>"음"</code>.',
 '함수 안 지역 n=100은 <b>밖에서 안 보인다</b> → 밖 n은 5.',
],
'heap|easy':[
 '<code>3*2=6</code>이 먼저 계산돼 x에 담긴다.',
 '마지막 번호는 2 → 30.',
 'b는 a의 별칭(같은 힙 객체) → a.v도 9. (원시면 각자 복사 — M4-1)',
 '<code>card.name</code> → <code>"민지"</code>.',
 '점을 이어 <code>data.inner.n</code> → 7.',
],
'heap|normal':[
 '없던 속성도 <code>=</code>로 추가 → 5.',
 '점을 이어 <code>d.in.v</code> → 7.',
 '<code>o[k]</code>는 k의 값 "score"를 키로 → <code>o.score=100</code>.',
 '<code>arr[0]</code>은 객체 → v를 9로 바꿔 9.',
 '<code>o.list.length</code> → 3.',
],
'heap|hard':[
 'x는 <code>o.n</code> 복사(5), a는 공유 → a.n=0이라도 <code>5+0=5</code>.',
 '점을 이어 <code>d.a.b.c</code> → 7.',
 '<b>배열은 참조</b> → b에 push하면 a도 늘어 4.',
 '<code>o.list[1].v</code> → 2.',
 '<code>delete</code>로 지운 키는 <code>undefined</code>.',
],
'passval|easy':[
 '원시값은 <b>복사본</b>이 전달 → 함수가 바꿔도 원본 money는 100.',
 '복사본만 999 → score는 50.',
 '복사본에만 +5 → a는 10.',
 '복사본만 0 → price는 200.',
 '복사본만 비움 → name은 <code>"민지"</code>.',
],
'passval|normal':[
 '복사본을 2배 → a는 5.',
 '복사본만 0 → s는 100.',
 '복사본에만 +5 → n은 10.',
 '복사본만 바뀜 → name은 <code>"민지"</code>.',
 '복사본만 false → flag는 true.',
],
'passval|hard':[
 '원시값을 바꾸려면 <b>반환값을 다시 담아야</b> → <code>a=dbl(a)=10</code>.',
 '함수가 바꿔도 원본 a는 7 → <code>a===7</code> true.',
 '복사본만 바뀌니 몇 번 불러도 a는 3.',
 't는 <code>"hi"</code> 그대로.',
 'a는 안 변해 4 → <code>inc(a)=5</code>, <code>5+4=9</code>.',
],
'passobj|easy':[
 '객체를 넘기면 <b>주소를 복사</b> → 함수 안 acc와 밖 wallet이 같은 객체 → money도 0.',
 '같은 객체라 user.name도 <code>"지훈"</code>.',
 '같은 객체라 hero.hp도 999.',
 '같은 객체라 task.ok도 true.',
 '같은 객체라 data.count도 0.',
],
'passobj|normal':[
 '같은 객체 → a.n도 5.',
 '중첩 객체도 공유 → me.pet.hp도 0.',
 '같은 배열 → list 개수 2.',
 '같은 객체 → d.n도 10.',
 '함수가 a를 바꾸면 별칭 b도 1(같은 객체).',
],
'passobj|hard':[
 '객체는 주소 공유 → 속성 변경이 원본에 샌다 → d.c는 0.',
 '<b>속성값(원시)만</b> 넘기면 그 값이 복사됨 → d.n은 5 안전. (객체 전체와 다름)',
 '<b>매개변수 재대입</b>은 지역 이름만 바꿀 뿐 → d는 원래 객체 그대로 5.',
 '중첩 객체도 공유 → me.pet.name은 <code>"루비"</code>.',
 '같은 배열 → arr[0]도 9.',
],
'passarr|easy':[
 '배열도 참조 → 같은 배열이라 arr도 늘어 3.',
 '같은 배열에 push → nums[0]은 9.',
 '같은 배열을 비움 → items 개수 0.',
 '같은 배열에 추가 → cart 개수 2.',
 '같은 배열의 0번 수정 → arr[0]은 10.',
],
'passarr|normal':[
 '같은 배열에 push → a[0]은 9.',
 '같은 배열을 비움 → 0.',
 '같은 배열 0번 수정 → 7.',
 '같은 배열에 추가 → 2.',
 '같은 배열에 둘 push → 2.',
],
'passarr|hard':[
 '같은 배열에 두 번 push → 3.',
 '<code>map</code>은 <b>새 배열만</b> 만들고 원본은 안 바꿈 → arr은 2.',
 '<b>매개변수 재대입</b>은 지역 이름만 → 원본 arr은 3 그대로.',
 'ref는 arr의 별칭(같은 배열) → push하면 arr도 2.',
 '같은 배열의 0번 +1 → 10.',
],
'graph|easy':[
 '<code>me.friend</code>는 효니와 같은 힙 객체 → 고치면 효니도 함께.',
 '점을 이어 <code>a.next.val</code> → 7.',
 '<code>y.ref</code>는 x와 같은 객체 → x.n도 9.',
 '<code>team.leader</code>는 p → 이름 <code>"김"</code>.',
 '점을 이어 끝까지 → 3.',
],
'graph|normal':[
 '점을 이어 <code>a.b.c</code> → 5.',
 '<code>p.next.next.v</code> → 9.',
 '<code>y.ref</code>는 x와 같은 객체 → x.n도 5.',
 '<code>g.link.val</code> → 3.',
 '<code>node.data.v</code> → 8.',
],
'graph|hard':[
 'a.x와 b.y가 <b>같은 노드 n</b>을 가리켜 → 한쪽 변경이 다른 쪽에도 → 9.',
 '4단계 경로 <code>r.c.c.c.v</code> → 7.',
 '<code>me.f</code>는 h와 같은 노드 → 고치면 h도 <code>"숏"</code>.',
 '<code>g.list[1].v</code> → 2.',
 '<code>d.items[0].name</code> → <code>"가"</code>.',
],
'friends|easy':[
 '<code>list[0]</code>은 minji와 같은 객체 → 바꾸면 minji도 <code>"X"</code>.',
 '<code>people[1].age</code> → 30.',
 '<code>arr[0]</code>은 a와 같은 객체 → a.hp도 50.',
 '<code>users[1].id</code> → 2.',
 '<code>cart[0].item</code> → <code>"빵"</code>.',
],
'friends|normal':[
 '<code>ppl[1].n</code> → 2.',
 '<code>list[0].name</code> → <code>"가"</code>.',
 '<code>arr[0]</code>은 m과 같은 객체 → m.hp도 0.',
 '<code>u[0].id</code> → 5.',
 '<code>c[1].item</code> → <code>"우유"</code>.',
],
'friends|hard':[
 '<code>arr[0]</code>은 a와 같은 객체 → a.hp도 50.',
 '<code>map</code>으로 나이만 뽑은 배열의 개수 2.',
 '<code>filter</code>로 25 초과 → 1명.',
 '<code>reduce</code>로 나이 합 → <code>20+30=50</code>.',
 '<code>g.members[0].n</code> → <code>"가"</code>.',
],
'family|easy':[
 '<code>me.parent.parent</code>는 할머니 → 이름 <code>"할머니"</code>.',
 '<code>a.child.child.name</code> → <code>"손자"</code>.',
 '<code>root.left.val</code> → 5.',
 '<code>me.mom.name</code> → <code>"엄마"</code>.',
 '<code>tree.node.node.data</code> → 7.',
],
'family|normal':[
 '<code>me.mom.name</code> → <code>"엄마"</code>.',
 '<code>r.left.val</code> → 5.',
 '<code>p.child.name</code> → <code>"자식"</code>.',
 '<code>r.right.val</code> → 8.',
 '<code>t.node.data</code> → 3.',
],
'family|hard':[
 '3대 경로 <code>me.parent.parent.name</code> → <code>"할"</code>.',
 '4단계 <code>t.l.l.l.v</code> → 7.',
 '<code>r.right.v</code> → 2.',
 'a.parent·b.parent가 <b>같은 dad</b> → 한쪽 변경이 둘 다 → <code>"X"</code>.',
 '<code>p.kids[1].name</code> → <code>"둘"</code>.',
],
'cycle|easy':[
 '<code>a.to</code>는 b → <code>b.val</code>이 9.',
 '<code>x.peer</code>는 y → id 2.',
 '<code>node.self</code>는 자기 자신 → v 7.',
 '<code>b.back</code>은 a → n 3.',
 '<code>p.q</code>는 q → name <code>"큐"</code>.',
],
'cycle|normal':[
 '<code>a.to</code>는 b → v 5.',
 '<code>x.p</code>는 y → id 2.',
 '<code>a.next</code>는 b → n 4.',
 '<code>b.back</code>은 a → n 3.',
 '<code>node.self</code>는 자기 → id 9.',
],
'cycle|hard':[
 '<code>a.to=b</code>, <code>b.to=a</code> → <code>b.to</code>는 a → a.v 1.',
 '<code>y.ref</code>는 x(순환) → x.n도 9.',
 '<code>n.self.self</code>도 결국 n → v 5.',
 '<code>a.next.next</code>는 a로 돌아옴 → id 1.',
 '<code>p.peer.peer</code>는 p로 돌아옴 → name <code>"P"</code>.',
],
'callstack|easy':[
 'b가 5, a가 2배 → 10. (b 프레임이 쌓였다 반환되고 a가 이어감)',
 'inner가 9, outer가 +1 → 10.',
 '<code>100 + 100*0.1 = 110</code>.',
 'b가 7을 그대로 전달 → 7.',
 'g가 4, f가 +1 → 5.',
],
'callstack|normal':[
 'a→b→c로 깊어졌다 c가 9를 반환 → 되돌아와 9.',
 'b가 2, a가 3배 → 6.',
 'b가 10, a가 -1 → 9.',
 'a가 3을 b로 넘기고 b가 2배 → 6.',
 'inc를 두 번 → <code>3→4→5</code>.',
],
'callstack|hard':[
 '지역 x=2와 b()=5를 곱 → 10.',
 '1&gt;0이라 b()를 부름 → 5.',
 '4단계 사슬 a→b→c→d, d가 8 → 8.',
 'd=2배를 두 번 → <code>3→6→12</code>.',
 'a=3, b=4 → <code>3+4=7</code>.',
],
'closure|easy':[
 '안쪽 함수가 바깥 c(100)를 <b>붙잡아</b> → <code>100-30=70</code>.',
 'n이 호출 사이 <b>기억</b>돼 → 세 번 불러 <code>1,2,3</code>.',
 'money(100)를 그대로 → 100.',
 'n(10)을 붙잡아 2배 → 20.',
 'v(3)를 붙잡아 +4 → 7.',
],
'closure|normal':[
 'v(3)를 붙잡아 +4 → 7.',
 '두 번 불러 <code>1,2</code>.',
 'mk(5)의 5를 붙잡아 2배 → 10.',
 'greeter의 name("z")을 붙잡아 <code>"hi z"</code>.',
 'm(100)을 붙잡아 -40 → 60.',
],
'closure|hard':[
 'adder(5)의 5를 붙잡고 y(3)도 받아 <code>5+3=8</code>.',
 'n이 누적 기억 → 세 번 불러 3.',
 '<b>클로저마다 자기 스코프</b> → a와 별개인 b는 처음이라 1.',
 'mult(3)의 3을 붙잡아 <code>4×3=12</code>.',
 'sum이 누적 → <code>10 다음 +20=30</code>.',
],
'gc|easy':[
 '<code>null</code>을 담아 <b>참조를 끊는다</b>(더 안 쓴다는 표시).',
 'data를 끊어도 <b>ref가 아직 가리켜</b> 객체는 살아 v=1.',
 '<code>null</code>로 참조를 끊는다.',
 'o를 끊어도 r이 가리켜 v=9.',
 'a를 끊어도 b가 가리켜 n=1.',
],
'gc|normal':[
 'a를 끊어도 b가 가리켜 n=1.',
 '<code>null</code>로 참조를 끊는다.',
 'o를 끊어도 r이 가리켜 list 개수 1.',
 'data를 끊어도 keep이 가리켜 v=5.',
 'x를 끊어도 y가 가리켜 n=9.',
],
'gc|hard':[
 'GC는 <b>아무도 안 가리키는 것만</b> 치운다. a를 끊어도 b가 가리켜 생존 → v=1.',
 'x를 끊어도 y가 가리켜 n=9.',
 'r이 배열 요소 객체를 붙잡아 → arr을 끊어도 v=5.',
 'c가 자식을 붙잡아 → root를 끊어도 v=3.',
 'x를 새 객체로 바꾸면 옛 것은 고아, 지금 x.n은 2.',
],
'class|easy':[
 '<code>new</code>가 힙에 객체를 만들고 constructor가 <code>this.n=5</code>.',
 '넘긴 인수가 <code>this.name</code>에 담겨 <code>"콩이"</code>.',
 '넘긴 인수 24가 age에.',
 'constructor의 <code>this.hp=100</code>.',
 '메서드 <code>bark()</code>가 <code>"멍"</code>을 반환.',
],
'class|normal':[
 '메서드 안 <code>this.name</code>은 자기 인스턴스 → <code>"hi z"</code>.',
 '<code>c.hp=50</code>으로 덮어써 50.',
 '두 번째 인수가 y → 3.',
 '<code>dbl</code>은 <code>this.n×2</code> → 10.',
 '15는 19 미만 → <code>"청소년"</code>.',
],
'class|hard':[
 '<code>new</code>마다 <b>힙에 다른 객체</b> → a·b는 별개, b.n은 0.',
 'B가 A를 물려받아(extends) A의 hi()를 그대로 → <code>"A"</code>.',
 '<code>ds[1]</code>은 두 번째 인스턴스 → <code>"나"</code>.',
 'c는 C로 만들어졌다 → <code>instanceof</code> true.',
 '<b>인스턴스도 그냥 객체</b> → <code>typeof="object"</code>. (class는 프로토타입 문법설탕)',
],
}
